import json
import time
import boto3
import urllib.request
import urllib.error
from datetime import datetime, timedelta

BUCKET = '2026-practices-agents'
FOLDER = 'News-Agent'
MAX_ITERATIONS = 20  # 7 coverage areas need more search turns
COMPACTION_THRESHOLD = 10  # compact after this many message pairs


def get_secret(secret_name):
    client = boto3.client('secretsmanager', region_name='us-east-1')
    value = client.get_secret_value(SecretId=secret_name)['SecretString']
    try:
        return list(json.loads(value).values())[0]
    except Exception:
        return value


def read_s3(key):
    try:
        s3 = boto3.client('s3')
        obj = s3.get_object(Bucket=BUCKET, Key=key)
        return obj['Body'].read().decode('utf-8')
    except Exception:
        return ""


def get_recent_digests():
    digests = ""
    for i in range(1, 4):
        date = (datetime.now() - timedelta(days=i)).strftime('%Y-%m-%d')
        content = read_s3(f'{FOLDER}/{date}.md')
        if content:
            digests += f"\n\n--- Digest {date} ---\n{content[:1000]}"
    return digests


def search_serper(query, serper_key):
    data = json.dumps({"q": query, "num": 5}).encode('utf-8')
    req = urllib.request.Request(
        "https://google.serper.dev/search",
        data=data,
        headers={
            'X-API-KEY': serper_key,
            'Content-Type': 'application/json'
        }
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as r:
            results = json.loads(r.read().decode('utf-8'))
    except urllib.error.HTTPError as e:
        print(f"[agent] Serper HTTP error {e.code}: {e.read().decode('utf-8')[:200]}")
        return f"Search failed (HTTP {e.code}) — skipping this query."
    except Exception as e:
        print(f"[agent] Serper error: {e}")
        return "Search unavailable — skipping this query."

    lines = []
    for item in results.get('organic', [])[:5]:
        title = item.get('title', '')
        snippet = item.get('snippet', '')
        url = item.get('link', '')
        if url:
            lines.append(f"- [{title}]({url}): {snippet}")
        else:
            lines.append(f"- {title}: {snippet}")
    return "\n".join(lines) if lines else "No results found."


def markdown_to_html(md: str) -> str:
    import re
    html = md
    html = re.sub(r'^## (.+)$', r'<h2>\1</h2>', html, flags=re.MULTILINE)
    html = re.sub(r'^### (.+)$', r'<h3>\1</h3>', html, flags=re.MULTILINE)
    html = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html)
    html = re.sub(r'\[(.+?)\]\((.+?)\)', r'<a href="\2">\1</a>', html)
    html = re.sub(r'^- (.+)$', r'<li>\1</li>', html, flags=re.MULTILINE)
    html = html.replace('\n\n', '</p><p>')
    return (
        '<html><body style="font-family:sans-serif;max-width:700px;margin:auto;padding:20px">'
        f'<p>{html}</p>'
        '</body></html>'
    )


def write_and_send(content, today, anthropic_key):
    full_content = f"# Industry Digest — {today}\n\n{content}\n\n---\n*Generated by news-feed-agent v3*"

    boto3.client('s3').put_object(
        Bucket=BUCKET,
        Key=f'{FOLDER}/{today}.md',
        Body=full_content.encode('utf-8'),
        ContentType='text/markdown'
    )
    print(f"[agent] Digest written to S3: {FOLDER}/{today}.md")

    html_body = markdown_to_html(full_content)

    ses = boto3.client('ses', region_name='us-east-1')
    try:
        ses.send_email(
            Source='gustavoarayas@gmail.com',
            Destination={'ToAddresses': ['gustavoarayas@gmail.com']},
            Message={
                'Subject': {'Data': f'Industry Digest — {today}'},
                'Body': {
                    'Text': {'Data': full_content},
                    'Html': {'Data': html_body}
                }
            }
        )
        print("[agent] Email sent via SES (HTML + text)")
    except Exception as e:
        print(f"[agent] SES send failed: {e}")

    return f"Digest written to S3 and emailed. File: {FOLDER}/{today}.md"


def call_claude_with_tools(system_prompt, messages, tools, api_key):
    """
    Calls Anthropic API with:
    - Prompt caching on system prompt and tool definitions
    - Retry with exponential backoff on 429 rate limit
    - Continuation loop if stop_reason == max_tokens
    """
    # System prompt as cacheable block — cached tokens cost 0.1x and use 0 ITPM
    cached_system = [
        {
            "type": "text",
            "text": system_prompt,
            "cache_control": {"type": "ephemeral"}
        }
    ]

    # Cache tool definitions — they never change within a session
    cached_tools = list(tools)
    if cached_tools:
        cached_tools[-1] = dict(cached_tools[-1], cache_control={"type": "ephemeral"})

    def _call(msgs):
        data = json.dumps({
            "model": "claude-fable-5",
            "max_tokens": 8000,          # was 2000 — raised to prevent truncation
            "system": cached_system,
            "tools": cached_tools,
            "messages": msgs
        }).encode('utf-8')

        req = urllib.request.Request(
            "https://api.anthropic.com/v1/messages",
            data=data,
            headers={
                'x-api-key': api_key,
                'anthropic-version': '2023-06-01',
                'anthropic-beta': 'prompt-caching-2024-07-31',
                'Content-Type': 'application/json'
            }
        )

        # Retry with exponential backoff on 429
        # Cap wait at 20s to avoid burning Lambda timeout budget
        for attempt in range(4):
            try:
                with urllib.request.urlopen(req, timeout=60) as r:
                    return json.loads(r.read().decode('utf-8'))
            except urllib.error.HTTPError as e:
                if e.code == 429:
                    wait = min(20 * (attempt + 1), 60)  # 20s, 40s, 60s, 60s max
                    print(f"[agent] Rate limit (429) — waiting {wait}s (attempt {attempt + 1}/4)")
                    time.sleep(wait)
                else:
                    print(f"[agent] Anthropic error {e.code}: {e.read().decode('utf-8')}")
                    raise
        raise Exception("[agent] Rate limit: max retries exceeded")

    # Continuation loop — if stop_reason is max_tokens, response was truncated
    # Keep appending and asking Claude to continue until stop_reason is end_turn or tool_use
    response = _call(messages)

    while response.get('stop_reason') == 'max_tokens':
        print("[agent] stop_reason: max_tokens — continuing truncated response")
        messages = list(messages)
        messages.append({"role": "assistant", "content": response['content']})
        messages.append({
            "role": "user",
            "content": "Continue exactly from where you left off, without repeating anything already written."
        })
        response = _call(messages)

    return response


def compact_messages(messages, system_prompt, api_key):
    """
    Summarises conversation history to prevent context bloat.
    Keeps the last 2 message pairs raw; summarises everything before.
    Called when message count exceeds COMPACTION_THRESHOLD.
    """
    if len(messages) <= 4:
        return messages

    to_summarise = messages[:-4]
    recent = messages[-4:]

    history_text = ""
    for m in to_summarise:
        role = m['role']
        content = m['content']
        if isinstance(content, list):
            # Tool results — extract text
            parts = []
            for block in content:
                if isinstance(block, dict):
                    parts.append(block.get('content', '') or str(block))
            history_text += f"\n[{role}]: {' | '.join(parts)}\n"
        else:
            history_text += f"\n[{role}]: {content}\n"

    summary_prompt = (
        "Summarise this agent conversation history in 3-5 bullet points. "
        "Include: topics searched, key findings, what has been done so far. "
        "Be concise — this summary replaces the full history.\n\n"
        f"{history_text}"
    )

    data = json.dumps({
        "model": "claude-haiku-4-5",   # Haiku for summarisation — cheaper and faster
        "max_tokens": 500,
        "messages": [{"role": "user", "content": summary_prompt}]
    }).encode('utf-8')

    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        data=data,
        headers={
            'x-api-key': api_key,
            'anthropic-version': '2023-06-01',
            'Content-Type': 'application/json'
        }
    )

    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            summary = json.loads(r.read().decode('utf-8'))['content'][0]['text']
        print(f"[agent] Context compacted: {len(to_summarise)} messages → 1 summary block")
        compacted = [{"role": "user", "content": f"[Previous session summary]\n{summary}"}]
        compacted.append({"role": "assistant", "content": "Understood. Continuing from the summary."})
        return compacted + recent
    except Exception as e:
        print(f"[agent] Compaction failed (non-fatal): {e}")
        return messages


TOOLS = [
    {
        "name": "search",
        "description": (
            "Search Google for recent news on a topic. "
            "Use this to find relevant articles, announcements, and developments. "
            "If results are weak or off-topic, call search again with a refined query."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "Specific Google search query. Be precise — include year or context if needed."
                }
            },
            "required": ["query"]
        }
    },
    {
        "name": "write_and_send",
        "description": (
            "Write the completed digest to S3 and send it by email. "
            "Call this only when you have gathered enough strong results across all required topics. "
            "The content must be a formatted markdown digest."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "description": "Full markdown digest content. Use headers and bullet points."
                }
            },
            "required": ["content"]
        }
    },
    {
        "name": "done",
        "description": "Signal that you are finished. Call this after write_and_send completes.",
        "input_schema": {
            "type": "object",
            "properties": {}
        }
        # cache_control added dynamically in call_claude_with_tools (last tool gets the cache marker)
    }
]


def run_agent(profile, recent_digests, serper_key, anthropic_key):
    today = datetime.now().strftime('%Y-%m-%d')

    system_prompt = f"""You are a research agent for a VP of Engineering at FrankieOne, a KYC/identity verification/fraud detection fintech in Melbourne.
Your job: produce a daily industry news digest by searching Google for relevant news and delivering it with working links.

Person's profile and interests:
{profile}

Recent digests (avoid repeating the same stories):
{recent_digests if recent_digests else "No previous digests available."}

Today's date: {today}

Instructions:
1. Search at least 5 different topics relevant to this person's interests.
2. Evaluate each result: is it relevant, recent, and substantive?
   - STRONG: directly relevant, recent (within 7 days), specific details
   - WEAK: generic, old, off-topic, or a listicle with no substance
3. If a search returns weak results, refine the query and search again.
4. Cover ALL of these areas, search at least one query per area:
   - Agentic AI & new model releases (Anthropic, OpenAI, Google)
   - Cybersecurity: threat intelligence, supply chain attacks, SDLC security, tooling (Wiz, Aikido, Netskope, SAST, SIEM)
   - Digital identity: KYC, IDV, biometrics, fraud detection, TDIF, IDSP, Digital ID Act 2024, AU/UK frameworks
   - Regulation & compliance: AML/CTF, AUSTRAC, open banking, fintech compliance in Australia and key markets
   - EU data sovereignty: GDPR enforcement, EU AI Act, data residency, cross-border transfer rulings (Schrems II, adequacy decisions)
   - AI-native software delivery: agentic coding, AI in the SDLC, engineering productivity research
   - Australian fintech and regtech industry news
5. Relevance bar is HIGH: skip generic tech news, listicles, and anything not directly tied to these areas. Fewer strong bullets beat many weak ones.
6. When satisfied with coverage, call write_and_send with a well-formatted markdown digest.
7. Then call done().

CRITICAL — link rules:
- The search tool returns results already formatted as markdown links: [Title](url)
- Copy those links directly into your digest — do not rewrite or fabricate URLs
- Every single bullet MUST include the article URL as a markdown link: **[Article Title](url)**
- Never write a bullet without a source link. If you don't have the URL, skip that bullet.

Digest format:
## 🔍 Topics Researched
(list all queries used)

## 🤖 Agentic AI & Models
## 🔒 Cybersecurity
## 🪪 Digital Identity & Fraud
## ⚖️ Regulation & Compliance
## 🚀 AI-Native Software Delivery
## 🇦🇺 Australian FinTech & RegTech

2-3 bullets per section. Format: **[Title](url)** — one sentence summary. Omit a section only if nothing strong was found, and say so."""

    messages = [{"role": "user", "content": "Please research and produce today's news digest."}]

    print(f"[agent] Starting agent loop. Max iterations: {MAX_ITERATIONS}")

    for i in range(MAX_ITERATIONS):
        print(f"[agent] Iteration {i + 1} | messages in context: {len(messages)}")

        # Compact context every COMPACTION_THRESHOLD turns to prevent ITPM buildup
        if i > 0 and i % COMPACTION_THRESHOLD == 0:
            messages = compact_messages(messages, system_prompt, anthropic_key)

        response = call_claude_with_tools(system_prompt, messages, TOOLS, anthropic_key)

        stop_reason = response.get('stop_reason')
        print(f"[agent] stop_reason: {stop_reason}")

        if stop_reason == 'end_turn':
            print("[agent] end_turn — loop complete")
            break

        if stop_reason != 'tool_use':
            print(f"[agent] Unexpected stop_reason: {stop_reason} — exiting")
            break

        messages.append({"role": "assistant", "content": response['content']})

        tool_results = []
        agent_done = False

        for block in response['content']:
            if block.get('type') != 'tool_use':
                continue

            tool_name = block['name']
            tool_input = block.get('input', {})
            tool_use_id = block['id']

            print(f"[agent] Tool: {tool_name} | input: {json.dumps(tool_input)[:120]}")

            if tool_name == 'search':
                result = search_serper(tool_input['query'], serper_key)
                tool_results.append({
                    "type": "tool_result",
                    "tool_use_id": tool_use_id,
                    "content": result
                })

            elif tool_name == 'write_and_send':
                result = write_and_send(tool_input['content'], today, anthropic_key)
                tool_results.append({
                    "type": "tool_result",
                    "tool_use_id": tool_use_id,
                    "content": result
                })

            elif tool_name == 'done':
                tool_results.append({
                    "type": "tool_result",
                    "tool_use_id": tool_use_id,
                    "content": "Agent marked as done."
                })
                agent_done = True

        if tool_results:
            messages.append({"role": "user", "content": tool_results})

        if agent_done:
            print("[agent] done() called — exiting loop")
            break

    else:
        print(f"[agent] Safety limit reached ({MAX_ITERATIONS} iterations)")

    print(f"[agent] Loop finished after {i + 1} iterations")
    return today


def lambda_handler(event, context):
    serper_key = get_secret('News_Agent_Serper_API_Key')
    anthropic_key = get_secret('Claude-Api-Key-News-Agent')

    profile = read_s3(f'{FOLDER}/context.md')
    recent_digests = get_recent_digests()

    today = run_agent(profile, recent_digests, serper_key, anthropic_key)

    return {'statusCode': 200, 'body': f'Agent completed. Digest: {FOLDER}/{today}.md'}
